const emojipedia = [
  {
    id: 1,
    emoji: "💪",
    name: "Tense Biceps",
    meaning:
      "“You can do that!” or “I feel strong!” Arm with tense biceps. Also used in connection with doing sports, e.g. at the gym."
  },
  {
    id: 2,
    emoji: "🙏",
    name: "Person With Folded Hands",
    meaning:
      "Two hands pressed together. Is currently very introverted, saying a prayer, or hoping for enlightenment. Is also used as a “high five” or to say thank you."
  },
  {
    id: 3,
    emoji: "🤣",
    name: "Rolling On The Floor, Laughing",
    meaning:
      "This is funny! A smiley face, rolling on the floor, laughing. The face is laughing boundlessly. The emoji version of “rofl“. Stands for „rolling on the floor, laughing“."
  },
  { id: 4,
  emoji: "😀",
  name: "Grinning Face",
  meaning: "A face with a big open (grinning) mouth, showing teeth."
},
{ id: 5, emoji: "😃", name: "Grinning Face with Big Eyes", meaning: "A face with a big open (grinning) mouth and wide eyes." },
{ id: 6, emoji: "😄", name: "Grinning Face with Smiling Eyes", meaning: "A face with a big open (grinning) mouth and smiling eyes." },
{ id: 7, emoji: "😁", name: "Beaming Face with Smiling Eyes", meaning: "A face with a big smile showing teeth and smiling eyes." },
{ id: 8, emoji: "😆", name: "Grinning Squinting Face", meaning: "A face with a big open (grinning) mouth and tightly closed eyes." },
{ id: 9, emoji: "😅", name: "Grinning Face with Sweat", meaning: "A face with a big open (grinning) mouth and a drop of sweat." },
{ id: 10, emoji: "😂", name: "Face with Tears of Joy", meaning: "A face laughing so hard that tears come out of its eyes." },
{ id: 11, emoji: "🤣", name: "Rolling on the Floor Laughing", meaning: "A face laughing boundlessly, rolling on the floor with joy." },
{ id: 12, emoji: "😊", name: "Smiling Face with Smiling Eyes", meaning: "A warm, happy smile with smiling eyes, conveying genuine happiness and warmth." },
{ id: 13, emoji: "😇", name: "Smiling Face with Halo", meaning: "A face with a halo, often representing innocence, kindness, or angelic behavior." },
{ id: 14, emoji: "🙂", name: "Slightly Smiling Face", meaning: "A face with a slight smile, often conveying a mild or neutral tone." },
{ id: 15, emoji: "🙃", name: "Upside-Down Face", meaning: "A face turned upside down, often conveying irony or silliness." },
{ id: 16, emoji: "😉", name: "Winking Face", meaning: "A face with one eye closed in a wink, often conveying playfulness or flirtation." },
{ id: 17, emoji: "😌", name: "Relieved Face", meaning: "A face with closed eyes and a relaxed smile, conveying a sense of relief." },
{ id: 18, emoji: "😍", name: "Smiling Face with Heart-Eyes", meaning: "A face with hearts for eyes, often conveying enthusiastic feelings of love, infatuation, and adoration." },
{ id: 19, emoji: "🥰", name: "Smiling Face with Hearts", meaning: "A face with smiling eyes and three hearts floating around, conveying affectionate feelings." },
{ id: 20, emoji: "😘", name: "Face Blowing a Kiss", meaning: "A face with one eye closed and lips puckered, blowing a kiss." },
{ id: 21, emoji: "😗", name: "Kissing Face", meaning: "A face with puckered lips, often conveying a kiss or whistling." },
{ id: 22, emoji: "😙", name: "Kissing Face with Smiling Eyes", meaning: "A face with puckered lips and smiling eyes, conveying a kiss." },
{ id: 23, emoji: "😚", name: "Kissing Face with Closed Eyes", meaning: "A face with puckered lips and closed eyes, conveying a more intimate kiss." },
{ id: 24, emoji: "😋", name: "Face Savoring Food", meaning: "A face with closed eyes and a big smile, often conveying the enjoyment of a delicious meal." },
{ id: 25, emoji: "😛", name: "Face with Tongue", meaning: "A face with a big open mouth and tongue sticking out, often conveying playfulness or teasing." },
{ id: 26, emoji: "😜", name: "Winking Face with Tongue", meaning: "A face with one eye closed in a wink and tongue sticking out, often conveying playfulness or teasing." },
{ id: 27, emoji: "🤪", name: "Zany Face", meaning: "A face with a big open mouth and eyes rolling in different directions, often conveying silliness or craziness." },
{ id: 28, emoji: "😝", name: "Squinting Face with Tongue", meaning: "A face with tightly closed eyes and tongue sticking out, often conveying extreme playfulness or teasing." },
{ id: 29, emoji: "🤑", name: "Money-Mouth Face", meaning: "A face with dollar signs for eyes and a green tongue, often conveying a love of money or wealth." },
{ id: 30, emoji: "🤗", name: "Hugging Face", meaning: "A face with open hands, often conveying a hug or warm embrace." },
{ id: 31, emoji: "🤭", name: "Face with Hand Over Mouth", meaning: "A face with a hand over the mouth, often conveying surprise, embarrassment, or keeping a secret." },
{ id: 32, emoji: "🤫", name: "Shushing Face", meaning: "A face with a finger over the mouth, often conveying a request for silence or secrecy." },
{ id: 33, emoji: "🤔", name: "Thinking Face", meaning: "A face with a hand on the chin, often conveying deep thought or pondering." },
{ id: 34, emoji: "🤐", name: "Zipper-Mouth Face", meaning: "A face with a closed zipper for a mouth, often conveying silence or the inability to speak." },
{ id: 35, emoji: "🤨", name: "Face with Raised Eyebrow", meaning: "A face with one raised eyebrow, often conveying skepticism or disbelief." },
{ id: 36, emoji: "😐", name: "Neutral Face", meaning: "A face with a straight mouth and neutral expression, often conveying a lack of emotion or indifference." },
{ id: 37, emoji: "😑", name: "Expressionless Face", meaning: "A face with a straight mouth and closed eyes, often conveying a lack of expression or emotion." },
{ id: 38, emoji: "😶", name: "Face Without Mouth", meaning: "A face without a mouth, often conveying silence or the inability to speak." },
{ id: 39, emoji: "😏", name: "Smirking Face", meaning: "A face with a sly, smug, or suggestive smile, often conveying a sense of self-satisfaction or mischief." },
{ id: 40, emoji: "😒", name: "Unamused Face", meaning: "A face with a slight frown and disinterested eyes, often conveying dissatisfaction or disapproval." },
{ id: 41, emoji: "🙄", name: "Face with Rolling Eyes", meaning: "A face with eyes rolled upwards, often conveying annoyance, disbelief, or disdain." },
{ id: 42, emoji: "😬", name: "Grimacing Face", meaning: "A face with a wide-open mouth and tightly closed eyes, often conveying discomfort or awkwardness." },
{ id: 43, emoji: "🤥", name: "Lying Face", meaning: "A face with a long nose, often conveying lying or dishonesty." },
{ id: 44, emoji: "😌", name: "Relieved Face", meaning: "A face with closed eyes and a relaxed smile, conveying a sense of relief." },
{ id: 45, emoji: "😔", name: "Pensive Face", meaning: "A face with a sad expression, often conveying deep thought or sadness." },
{ id: 46, emoji: "😪", name: "Sleepy Face", meaning: "A face with closed eyes and a drooping mouth, often conveying sleepiness or fatigue." },
{ id: 47, emoji: "🤤", name: "Drooling Face", meaning: "A face with drooling mouth, often conveying desire or longing." },
{ id: 48, emoji: "😴", name: "Sleeping Face", meaning: "A face with closed eyes and mouth, often conveying sleep or rest." },
{ id: 49, emoji: "😷", name: "Face with Medical Mask", meaning: "A face with a medical mask, often conveying sickness or protection against illness." },
{ id: 50, emoji: "🤒", name: "Face with Thermometer", meaning: "A face with a thermometer, often conveying sickness or fever." },
{ id: 51, emoji: "🤕", name: "Face with Head-Bandage", meaning: "A face with a bandage on the head, often conveying injury or pain." },
{ id: 52, emoji: "🤢", name: "Nauseated Face", meaning: "A face with a greenish hue, often conveying nausea or disgust." },
{ id: 53, emoji: "🤮", name: "Face Vomiting", meaning: "A face with vomit coming out, often conveying extreme disgust or sickness." },
{ id: 54, emoji: "🍅", name: "Tomato", meaning: "A ripe red tomato, often used in salads and sauces." },
{ id: 55, emoji: "🥔", name: "Potato", meaning: "A brown potato, often used in a variety of dishes." },
{ id: 56, emoji: "🥕", name: "Carrot", meaning: "An orange carrot, a root vegetable known for its crunchiness." },
{ id: 57, emoji: "🌽", name: "Corn", meaning: "An ear of corn, a common vegetable often eaten on the cob." },
{ id: 58, emoji: "🥒", name: "Cucumber", meaning: "A green cucumber, often used in salads and sandwiches." },
{ id: 59, emoji: "🥬", name: "Leafy Green", meaning: "A leafy green vegetable, often representing lettuce, spinach, or other greens." },
{ id: 60, emoji: "🥦", name: "Broccoli", meaning: "A head of broccoli, a green vegetable often used in various dishes." },
{ id: 61, emoji: "🍆", name: "Eggplant", meaning: "A purple eggplant, also known as aubergine, used in various cuisines." },
{ id: 62, emoji: "🌶️", name: "Hot Pepper", meaning: "A red chili pepper, known for its spiciness." },
{ id: 63, emoji: "🫑", name: "Bell Pepper", meaning: "A bell pepper, which can be red, yellow, green, or orange." },
{ id: 64, emoji: "🥑", name: "Avocado", meaning: "A green avocado, often used in salads, sandwiches, and guacamole." },
{ id: 65, emoji: "🍄", name: "Mushroom", meaning: "A brown mushroom, often used in cooking." },
{ id: 66, emoji: "🥜", name: "Peanuts", meaning: "Shelled peanuts, often representing the nut or peanut butter." },
{ id: 67, emoji: "🌰", name: "Chestnut", meaning: "A brown chestnut, often used in cooking or as a snack." },
{ id: 68, emoji: "🧄", name: "Garlic", meaning: "A bulb of garlic, often used to add flavor to dishes." },
{ id: 69, emoji: "🧅", name: "Onion", meaning: "A bulb onion, often used in a variety of dishes for flavor." },
{ id: 70, emoji: "🥥", name: "Coconut", meaning: "A brown coconut, known for its white flesh and water." },
{ id: 71, emoji: "🍋", name: "Lemon", meaning: "A yellow lemon, often used for its juice and zest." },
{ id: 72, emoji: "🍌", name: "Banana", meaning: "A ripe yellow banana, a popular fruit." },
{ id: 73, emoji: "🍍", name: "Pineapple", meaning: "A tropical fruit with a spiky exterior and sweet interior." },
{ id: 74, emoji: "🥭", name: "Mango", meaning: "A ripe mango, a tropical fruit known for its sweetness." },
{ id: 75, emoji: "🍑", name: "Peach", meaning: "A juicy peach, often used in desserts and snacks." },
{ id: 76, emoji: "🍒", name: "Cherries", meaning: "A pair of cherries, often representing the fruit or its flavor." },
{ id: 77, emoji: "🍇", name: "Grapes", meaning: "A bunch of grapes, often used to make wine or eaten as a snack." },
{ id: 78, emoji: "🍉", name: "Watermelon", meaning: "A slice of watermelon, a refreshing summer fruit." },
{ id: 79, emoji: "🍓", name: "Strawberry", meaning: "A ripe strawberry, a popular fruit often eaten fresh or in desserts." },
{ id: 80, emoji: "🍈", name: "Melon", meaning: "A melon, often representing cantaloupe or honeydew." },
{ id: 81, emoji: "🍏", name: "Green Apple", meaning: "A green apple, often representing the Granny Smith variety." },
{ id: 82, emoji: "🍎", name: "Red Apple", meaning: "A red apple, often used as a symbol of health and knowledge." },
{ id: 83, emoji: "🍐", name: "Pear", meaning: "A ripe pear, often eaten fresh or used in desserts." },
{ id: 84, emoji: "🍊", name: "Tangerine", meaning: "A tangerine, a small citrus fruit often eaten as a snack." },
{ id: 85, emoji: "🚗", name: "Car", meaning: "A red car, often used to represent personal transportation." },
{ id: 86, emoji: "🚕", name: "Taxi", meaning: "A yellow taxi cab, often used for public transportation in cities." },
{ id: 87, emoji: "🚙", name: "SUV", meaning: "A sport utility vehicle, often used for family trips and off-road driving." },
{ id: 88, emoji: "🚌", name: "Bus", meaning: "A large vehicle used for public transportation." },
{ id: 89, emoji: "🚎", name: "Trolleybus", meaning: "A bus powered by overhead electric wires." },
{ id: 90, emoji: "🏎️", name: "Racing Car", meaning: "A fast racing car, often used in motorsports." },
{ id: 91, emoji: "🚓", name: "Police Car", meaning: "A police car, often used to represent law enforcement." },
{ id: 92, emoji: "🚑", name: "Ambulance", meaning: "An emergency vehicle used to transport people to hospitals." },
{ id: 93, emoji: "🚒", name: "Fire Truck", meaning: "A fire engine used by firefighters." },
{ id: 94, emoji: "🚐", name: "Minivan", meaning: "A van, often used for transporting groups of people or goods." },
{ id: 95, emoji: "🚚", name: "Delivery Truck", meaning: "A truck used for delivering goods." },
{ id: 96, emoji: "🚛", name: "Articulated Lorry", meaning: "A large truck with a trailer, often used for long-distance transportation of goods." },
{ id: 97, emoji: "🚜", name: "Tractor", meaning: "A vehicle used for farming and agricultural purposes." },
{ id: 98, emoji: "🛴", name: "Kick Scooter", meaning: "A small scooter powered by pushing with one foot." },
{ id: 99, emoji: "🚲", name: "Bicycle", meaning: "A two-wheeled vehicle powered by pedaling." },
{ id: 100, emoji: "🛵", name: "Motor Scooter", meaning: "A small motorized scooter often used in urban areas." },
{ id: 101, emoji: "🏍️", name: "Motorcycle", meaning: "A two-wheeled motor vehicle often used for personal transportation." },
{ id: 102, emoji: "🚨", name: "Police Car Light", meaning: "A flashing light used by police cars, often representing emergencies." },
{ id: 103, emoji: "🚍", name: "Oncoming Bus", meaning: "A bus facing the viewer, often representing public transportation." },
{ id: 104, emoji: "🚔", name: "Oncoming Police Car", meaning: "A police car facing the viewer, often used to represent law enforcement." },
{ id: 105, emoji: "🚍", name: "Oncoming Fire Truck", meaning: "A fire truck facing the viewer, used by firefighters." },
{ id: 106, emoji: "🚖", name: "Oncoming Taxi", meaning: "A taxi cab facing the viewer, representing urban transportation." },
{ id: 107, emoji: "🚘", name: "Oncoming Automobile", meaning: "A car facing the viewer, representing personal transportation." },
{ id: 108, emoji: "🚡", name: "Aerial Tramway", meaning: "A cable car used to transport people in mountainous areas." },
{ id: 109, emoji: "🚠", name: "Mountain Cableway", meaning: "A cable car used to transport people up and down mountains." },
{ id: 110, emoji: "🚟", name: "Suspension Railway", meaning: "A train suspended from a track, often used in urban areas." },
{ id: 111, emoji: "🚃", name: "Railway Car", meaning: "A passenger car on a train, often used in public transportation." },
{ id: 112, emoji: "🚋", name: "Tram Car", meaning: "A tram used for public transportation in cities." },
{ id: 113, emoji: "🚝", name: "Monorail", meaning: "A train that runs on a single track, often used in urban areas." },
{ id: 114, emoji: "🚄", name: "High-Speed Train", meaning: "A fast train, often used for long-distance travel." },
{ id: 115, emoji: "🚅", name: "Bullet Train", meaning: "A high-speed train, often associated with Japan." },
{ id: 116, emoji: "🚈", name: "Light Rail", meaning: "A light rail train, often used in cities." },
{ id: 117, emoji: "🚞", name: "Mountain Railway", meaning: "A train used to transport people through mountainous regions." },
{ id: 118, emoji: "🚂", name: "Locomotive", meaning: "A steam-powered train engine, often used in the past." },
{ id: 119, emoji: "🚆", name: "Train", meaning: "A train, often used for public transportation." },
{ id: 120, emoji: "🚇", name: "Metro", meaning: "An underground train, often used in cities." },
{ id: 121, emoji: "❤️", name: "Red Heart", meaning: "A red heart symbolizing love and affection." },
{ id: 122, emoji: "🧡", name: "Orange Heart", meaning: "An orange heart symbolizing warmth and enthusiasm." },
{ id: 123, emoji: "💛", name: "Yellow Heart", meaning: "A yellow heart symbolizing happiness and friendship." },
{ id: 124, emoji: "💚", name: "Green Heart", meaning: "A green heart symbolizing nature and growth." },
{ id: 125, emoji: "💙", name: "Blue Heart", meaning: "A blue heart symbolizing trust and tranquility." },
{ id: 126, emoji: "💜", name: "Purple Heart", meaning: "A purple heart symbolizing compassion and creativity." },
{ id: 127, emoji: "🤎", name: "Brown Heart", meaning: "A brown heart symbolizing stability and dependability." },
{ id: 128, emoji: "🖤", name: "Black Heart", meaning: "A black heart symbolizing deep emotions or mourning." },
{ id: 129, emoji: "🤍", name: "White Heart", meaning: "A white heart symbolizing purity and peace." },
{ id: 130, emoji: "💔", name: "Broken Heart", meaning: "A broken heart symbolizing sadness or heartbreak." },
{ id: 131, emoji: "❤️‍🔥", name: "Heart on Fire", meaning: "A heart engulfed in flames, symbolizing intense love or passion." },
{ id: 132, emoji: "❤️‍🩹", name: "Mending Heart", meaning: "A heart with a bandage, symbolizing healing or recovering from a broken heart." },
{ id: 133, emoji: "💌", name: "Love Letter", meaning: "An envelope with a heart symbol, often used to represent love letters or romantic messages." },
{ id: 134, emoji: "💖", name: "Sparkling Heart", meaning: "A sparkling pink heart symbolizing a special and exciting love." },
{ id: 135, emoji: "💗", name: "Growing Heart", meaning: "A heart with a gradient effect, symbolizing growing love or affection." },
{ id: 136, emoji: "💘", name: "Heart with Arrow", meaning: "A heart pierced by an arrow, symbolizing being struck by love." },
{ id: 137, emoji: "💞", name: "Revolving Hearts", meaning: "Two hearts revolving around each other, symbolizing mutual love and affection." },
{ id: 138, emoji: "💕", name: "Two Hearts", meaning: "Two hearts, often used to represent romantic love or affection." },
{ id: 139, emoji: "💑", name: "Couple with Heart", meaning: "A couple holding hands with a heart between them, symbolizing romantic relationships." },
{ id: 140, emoji: "👩‍❤️‍👨", name: "Woman and Man Holding Hands", meaning: "A couple, a woman and a man holding hands, symbolizing romantic partnership." },
{ id: 141, emoji: "👩‍❤️‍👩", name: "Woman with Woman Heart", meaning: "A couple of women holding hands with a heart between them, symbolizing romantic love." },
{ id: 142, emoji: "👨‍❤️‍👨", name: "Man with Man Heart", meaning: "A couple of men holding hands with a heart between them, symbolizing romantic love." },
{ id: 143, emoji: "👩‍❤️‍🧑", name: "Woman and Man with Heart", meaning: "A couple with a heart symbol, representing love and romantic relationships." },
{ id: 144, emoji: "💍", name: "Ring", meaning: "A diamond ring, often used to represent engagement or marriage." },
{ id: 145, emoji: "💎", name: "Gem Stone", meaning: "A sparkling gem, often symbolizing luxury or value." },
{ id: 146, emoji: "✨", name: "Sparkles", meaning: "A group of sparkling stars, symbolizing something special or magical." },
{ id: 147, emoji: "⭐", name: "Star", meaning: "A five-pointed star, often representing excellence or admiration." },
{ id: 148, emoji: "🌟", name: "Glowing Star", meaning: "A star with a glow around it, symbolizing something that stands out or is exceptional." },
{ id: 149, emoji: "🌠", name: "Shooting Star", meaning: "A star with a trail, often symbolizing wishes or fleeting moments." },
{ id: 150, emoji: "🌌", name: "Milky Way", meaning: "A depiction of the Milky Way galaxy, symbolizing vastness or a dreamlike quality." },
{ id: 151, emoji: "🎇", name: "Fireworks", meaning: "Colorful fireworks exploding in the sky, symbolizing celebration or festivity." },
{ id: 152, emoji: "🎆", name: "Fireworks Sparkler", meaning: "A sparkler firework, often used to celebrate special occasions." },
{ id: 153, emoji: "🎑", name: "Moon Viewing Ceremony", meaning: "A traditional Japanese festival to view the full moon, symbolizing harvest and seasonal change." },
{ id: 154, emoji: "🎃", name: "Jack-O-Lantern", meaning: "A carved pumpkin with a face, often used to celebrate Halloween." },
{ id: 155, emoji: "🎄", name: "Christmas Tree", meaning: "A decorated Christmas tree, symbolizing the holiday season." },
{ id: 156, emoji: "🎈", name: "Balloon", meaning: "A colorful balloon, often used for celebrations or parties." },
{ id: 157, emoji: "🎉", name: "Party Popper", meaning: "A party popper releasing confetti, symbolizing celebration and joy." },
{ id: 158, emoji: "🎊", name: "Confetti Ball", meaning: "A ball of confetti, often used to celebrate events and achievements." },
{ id: 159, emoji: "🎁", name: "Gift", meaning: "A wrapped gift, often representing presents and special occasions." },
{ id: 160, emoji: "🎫", name: "Ticket", meaning: "A ticket stub, often representing entry or admission to events." },
{ id: 161, emoji: "🔮", name: "Crystal Ball", meaning: "A crystal ball, often used to symbolize fortune-telling or magic." },
{ id: 162, emoji: "🧩", name: "Puzzle Piece", meaning: "A single puzzle piece, representing problem-solving or completion." },
{ id: 163, emoji: "🧸", name: "Teddy Bear", meaning: "A stuffed teddy bear, symbolizing comfort and childhood." },
{ id: 164, emoji: "🧵", name: "Thread", meaning: "A spool of thread, often used for sewing or crafting." },
{ id: 165, emoji: "🧶", name: "Yarn", meaning: "A ball of yarn, often used for knitting or crocheting." },
{ id: 166, emoji: "🪀", name: "Yo-Yo", meaning: "A yo-yo toy, symbolizing playfulness and skill." },
{ id: 167, emoji: "🔑", name: "Key", meaning: "A key, often representing access or unlocking something." },
{ id: 168, emoji: "🗝️", name: "Old Key", meaning: "An antique key, symbolizing historical or valuable access." },
{ id: 169, emoji: "🔒", name: "Lock", meaning: "A padlock, symbolizing security or restriction." },
{ id: 170, emoji: "🔓", name: "Unlocked", meaning: "An unlocked padlock, representing freedom or access." },
{ id: 171, emoji: "🔏", name: "Lock with Ink Pen", meaning: "A padlock with an ink pen, symbolizing privacy or confidential writing." },
{ id: 172, emoji: "🔐", name: "Key with Lock", meaning: "A key and a lock, symbolizing security and access control." },
{ id: 173, emoji: "🔍", name: "Magnifying Glass Tilted Left", meaning: "A magnifying glass tilted left, representing search or investigation." },
{ id: 174, emoji: "🔎", name: "Magnifying Glass Tilted Right", meaning: "A magnifying glass tilted right, symbolizing detailed examination." },
{ id: 175, emoji: "🔏", name: "Lock with Ink Pen", meaning: "A padlock with an ink pen, symbolizing privacy or confidential writing." },
{ id: 176, emoji: "🔐", name: "Key with Lock", meaning: "A key and a lock, symbolizing security and access control." },
{ id: 177, emoji: "🚦", name: "Traffic Light", meaning: "A traffic light, used to control the flow of vehicles and pedestrians at intersections." },
{ id: 178, emoji: "🚥", name: "Horizontal Traffic Light", meaning: "A horizontal traffic light, used in some regions to control vehicle and pedestrian traffic." },
{ id: 179, emoji: "🚧", name: "Construction Sign", meaning: "A construction barrier, indicating roadwork or obstacles." },
{ id: 180, emoji: "🔰", name: "Japanese Symbol for Beginner", meaning: "A symbol used to indicate beginner-level drivers or learners." },
{ id: 181, emoji: "⛔", name: "No Entry", meaning: "A no entry sign, indicating that access is prohibited." },
{ id: 182, emoji: "🚫", name: "Prohibited", meaning: "A prohibition sign, indicating that certain actions or behaviors are not allowed." },
{ id: 183, emoji: "🚭", name: "No Smoking", meaning: "A no smoking sign, indicating that smoking is not permitted in the area." },
{ id: 184, emoji: "🛑", name: "Stop Sign", meaning: "A stop sign, instructing drivers to come to a complete stop at an intersection." },
{ id: 185, emoji: "⚠️", name: "Warning", meaning: "A warning sign, used to alert drivers and pedestrians to potential hazards." },
{ id: 186, emoji: "🚔", name: "Police Car", meaning: "A police car, used to represent law enforcement or emergency response." },
{ id: 187, emoji: "🚓", name: "Oncoming Police Car", meaning: "An oncoming police car, used to represent law enforcement or emergency response." },
{ id: 188, emoji: "🚕", name: "Taxi", meaning: "A yellow taxi cab, used for public transportation in urban areas." },
{ id: 189, emoji: "🚗", name: "Car", meaning: "A car, used to represent personal transportation." },
{ id: 190, emoji: "🚙", name: "SUV", meaning: "A sport utility vehicle, used for family trips and off-road driving." },
{ id: 191, emoji: "🚚", name: "Delivery Truck", meaning: "A delivery truck, used for transporting goods and packages." },
{ id: 192, emoji: "🚛", name: "Articulated Lorry", meaning: "A large lorry or truck, used for heavy cargo transport." },
{ id: 193, emoji: "🚜", name: "Tractor", meaning: "A tractor, used for agricultural or construction purposes." },
{ id: 194, emoji: "🚌", name: "Bus", meaning: "A bus, used for public transportation in cities and towns." },
{ id: 195, emoji: "🚎", name: "Trolleybus", meaning: "A trolleybus, a type of bus that draws power from twin wires overhead." },
{ id: 196, emoji: "🚆", name: "Train", meaning: "A train, used for long-distance or commuter travel." },
{ id: 197, emoji: "🚇", name: "Metro", meaning: "A metro train, used for urban rapid transit." },
{ id: 198, emoji: "🚈", name: "Light Rail", meaning: "A light rail vehicle, used for urban transit systems." },
{ id: 199, emoji: "🚉", name: "Station", meaning: "A railway station, where passengers board or alight from trains." },
{ id: 200, emoji: "🚂", name: "Locomotive", meaning: "A locomotive, used for pulling trains on railways." },
{ id: 201, emoji: "🚆", name: "Train", meaning: "A train, used for long-distance travel." },
{ id: 202, emoji: "🚅", name: "High-Speed Train", meaning: "A high-speed train, used for rapid long-distance travel." },
{ id: 203, emoji: "🚄", name: "Bullet Train", meaning: "A bullet train, known for its high speed and sleek design." },
{ id: 204, emoji: "🚝", name: "Monorail", meaning: "A monorail train, which operates on a single rail." },
{ id: 205, emoji: "🚋", name: "Tram", meaning: "A tram, used for public transportation in urban areas." },
{ id: 206, emoji: "🚞", name: "Mountain Railway", meaning: "A mountain railway train, used for travel in mountainous regions." },
{ id: 207, emoji: "🚟", name: "Suspension Railway", meaning: "A suspension railway, where trains are suspended from overhead tracks." },
{ id: 208, emoji: "🚠", name: "Cable Car", meaning: "A cable car, used for transporting passengers up hills or mountains." },
{ id: 209, emoji: "🚡", name: "Aerial Tramway", meaning: "An aerial tramway, used for transporting passengers across valleys or rivers." },
{ id: 210, emoji: "🚢", name: "Ship", meaning: "A ship, used for travel over water." },
{ id: 211, emoji: "⛴️", name: "Ferry", meaning: "A ferry, used for transporting passengers and vehicles across bodies of water." },
{ id: 212, emoji: "🚤", name: "Speedboat", meaning: "A speedboat, used for fast travel on water." },
{ id: 213, emoji: "🚀", name: "Rocket", meaning: "A rocket, used for space travel or as a symbol of rapid progress." },
{ id: 214, emoji: "🛸", name: "Flying Saucer", meaning: "A flying saucer, often used to represent UFOs or science fiction." },
{ id: 215, emoji: "🛳", name: "Boat", meaning: "A boat, used for travel or recreation on water." },
{ id: 216, emoji: "⛵", name: "Sailboat", meaning: "A sailboat, used for sailing or leisurely water activities." },
{ id: 217, emoji: "👋", name: "Waving Hand", meaning: "A hand waving, used to greet someone or say goodbye." },
{ id: 218, emoji: "🤚", name: "Raised Back of Hand", meaning: "A hand with the palm facing out, often used for a greeting or stop gesture." },
{ id: 219, emoji: "🖐️", name: "Hand with Fingers Raised", meaning: "A hand with fingers raised, used for greeting or signaling." },
{ id: 220, emoji: "✋", name: "Raised Hand", meaning: "A hand raised, often used to get attention or as a greeting." },
{ id: 221, emoji: "👌", name: "OK Hand", meaning: "A hand gesture indicating approval or that everything is fine." },
{ id: 222, emoji: "🤝", name: "Handshake", meaning: "Two hands clasped together, symbolizing a handshake or agreement." },
{ id: 223, emoji: "🙌", name: "Raising Hands", meaning: "Two hands raised in the air, often used to celebrate or show excitement." },
{ id: 224, emoji: "👏", name: "Clapping Hands", meaning: "Two hands clapping together, used to show appreciation or congratulations." },
{ id: 225, emoji: "🙏", name: "Folded Hands", meaning: "Two hands pressed together, often used to say thank you or as a gesture of prayer." },
{ id: 226, emoji: "🤲", name: "Palms Up Together", meaning: "Hands with palms facing up, used for offering or receiving something." },
{ id: 227, emoji: "🤝", name: "Handshake", meaning: "Two hands clasped together in a handshake, symbolizing greeting or agreement." },
{ id: 228, emoji: "🙋", name: "Person Raising Hand", meaning: "A person raising one hand, used to indicate a question or to get attention." },
{ id: 229, emoji: "🙋‍♂️", name: "Man Raising Hand", meaning: "A man raising one hand, used to indicate a question or to get attention." },
{ id: 230, emoji: "🙋‍♀️", name: "Woman Raising Hand", meaning: "A woman raising one hand, used to indicate a question or to get attention." },
{ id: 231, emoji: "🖖", name: "Vulcan Salute", meaning: "A hand gesture with the fingers parted, used as a greeting in the Star Trek universe." },
{ id: 232, emoji: "🖐️", name: "Hand with Fingers Raised", meaning: "A hand with fingers raised, used for greeting or signaling." },
{ id: 233, emoji: "👐", name: "Open Hands", meaning: "Two open hands, used to represent giving or receiving." },
{ id: 234, emoji: "🤗", name: "Hugging Face", meaning: "A face with open hands, used to represent hugging or affection." },
{ id: 235, emoji: "🤠", name: "Cowboy Hat Face", meaning: "A face wearing a cowboy hat, used to convey a friendly or adventurous greeting." },
{ id: 236, emoji: "🤩", name: "Star-Struck", meaning: "A face with star eyes, used to show excitement or admiration." },
{ id: 237, emoji: "😎", name: "Sunglasses Face", meaning: "A face with sunglasses, used to convey coolness or a relaxed attitude." },
{ id: 238, emoji: "😃", name: "Grinning Face with Big Eyes", meaning: "A face with a big smile and wide eyes, used to express happiness or friendliness." },
{ id: 239, emoji: "😄", name: "Grinning Face with Smiling Eyes", meaning: "A face with a big smile and closed eyes, used to express joy or contentment." },
{ id: 240, emoji: "😁", name: "Beaming Face with Smiling Eyes", meaning: "A face with a broad smile and eyes squinted in happiness." },
{ id: 241, emoji: "😅", name: "Grinning Face with Sweat", meaning: "A face with a nervous smile and sweat, used to express relief or nervousness." },
{ id: 242, emoji: "😂", name: "Face with Tears of Joy", meaning: "A face laughing so hard that it’s crying, used to show something is extremely funny." },
{ id: 243, emoji: "🤣", name: "Rolling on the Floor Laughing", meaning: "A face laughing so hard it’s rolling on the floor, used to show something is hilarious." },
{ id: 244, emoji: "😊", name: "Smiling Face with Smiling Eyes", meaning: "A face with a gentle smile and closed eyes, used to convey warmth and friendliness." },
{ id: 245, emoji: "🐶", name: "Dog", meaning: "A dog, often representing pets or loyalty." },
{ id: 246, emoji: "🐱", name: "Cat", meaning: "A cat, often representing pets or independence." },
{ id: 247, emoji: "🐭", name: "Mouse", meaning: "A mouse, often representing small animals or shyness." },
{ id: 248, emoji: "🐹", name: "Hamster", meaning: "A hamster, often representing small pets or cuteness." },
{ id: 249, emoji: "🐰", name: "Rabbit", meaning: "A rabbit, often representing gentleness or Easter." },
{ id: 250, emoji: "🦊", name: "Otter", meaning: "An otter, often representing playfulness or water animals." },
{ id: 251, emoji: "🐻", name: "Bear", meaning: "A bear, often representing strength or nature." },
{ id: 252, emoji: "🐼", name: "Panda", meaning: "A panda, often representing cuteness or endangered species." },
{ id: 253, emoji: "🐨", name: "Koala", meaning: "A koala, often representing Australia or cuddly animals." },
{ id: 254, emoji: "🐯", name: "Tiger", meaning: "A tiger, often representing strength or the wild." },
{ id: 255, emoji: "🦁", name: "Lion", meaning: "A lion, often representing bravery or royalty." },
{ id: 256, emoji: "🐮", name: "Cow", meaning: "A cow, often representing farming or agriculture." },
{ id: 257, emoji: "🐷", name: "Pig", meaning: "A pig, often representing abundance or farm animals." },
{ id: 258, emoji: "🐸", name: "Frog", meaning: "A frog, often representing amphibians or transformation." },
{ id: 259, emoji: "🐵", name: "Monkey", meaning: "A monkey, often representing playfulness or primates." },
{ id: 260, emoji: "🙈", name: "See-No-Evil Monkey", meaning: "A monkey covering its eyes, representing the concept of 'see no evil'." },
{ id: 261, emoji: "🙉", name: "Hear-No-Evil Monkey", meaning: "A monkey covering its ears, representing the concept of 'hear no evil'." },
{ id: 262, emoji: "🙊", name: "Speak-No-Evil Monkey", meaning: "A monkey covering its mouth, representing the concept of 'speak no evil'." },
{ id: 263, emoji: "🐔", name: "Chicken", meaning: "A chicken, often representing farm animals or poultry." },
{ id: 264, emoji: "🐧", name: "Penguin", meaning: "A penguin, often representing cold climates or cuteness." },
{ id: 265, emoji: "🦅", name: "Eagle", meaning: "An eagle, often representing freedom or strength." },
{ id: 266, emoji: "🦉", name: "Owl", meaning: "An owl, often representing wisdom or night time." },
{ id: 267, emoji: "🦤", name: "Feather", meaning: "A feather, often representing birds or lightness." },
{ id: 268, emoji: "🐴", name: "Horse", meaning: "A horse, often representing strength or travel." },
{ id: 269, emoji: "🦄", name: "Unicorn", meaning: "A unicorn, often representing magic or fantasy." },
{ id: 270, emoji: "🐝", name: "Bee", meaning: "A bee, often representing nature or pollination." },
{ id: 271, emoji: "🦋", name: "Butterfly", meaning: "A butterfly, often representing transformation or beauty." },
{ id: 272, emoji: "🌻", name: "Sunflower", meaning: "A sunflower, often representing nature or happiness." },
{ id: 273, emoji: "🌷", name: "Tulip", meaning: "A tulip, often representing spring or flowers." },
{ id: 274, emoji: "🌹", name: "Rose", meaning: "A rose, often representing love or romance." },
{ id: 275, emoji: "🌺", name: "Hibiscus", meaning: "A hibiscus flower, often representing tropical climates or beauty." },
{ id: 276, emoji: "🌸", name: "Cherry Blossom", meaning: "A cherry blossom, often representing spring or Japanese culture." },
{ id: 277, emoji: "🌼", name: "Blossom", meaning: "A generic blossom, representing flowers or growth." },
{ id: 278, emoji: "🌾", name: "Sheaf of Rice", meaning: "A sheaf of rice, often representing agriculture or harvest." },
{ id: 279, emoji: "🌿", name: "Herb", meaning: "An herb, often representing plants or gardening." },
{ id: 280, emoji: "🍀", name: "Four Leaf Clover", meaning: "A four-leaf clover, often representing luck or good fortune." },
{ id: 281, emoji: "🍁", name: "Maple Leaf", meaning: "A maple leaf, often representing autumn or nature." },
{ id: 282, emoji: "🍂", name: "Fallen Leaf", meaning: "A fallen leaf, often representing autumn or change." },
{ id: 283, emoji: "🍃", name: "Leaf Fluttering in the Wind", meaning: "A leaf fluttering in the wind, often representing nature or transition." },
{ id: 284, emoji: "🌍", name: "Earth Globe Europe-Africa", meaning: "The Earth globe focused on Europe and Africa, often representing the world or geography." },
{ id: 285, emoji: "🌎", name: "Earth Globe Americas", meaning: "The Earth globe focused on the Americas, often representing the world or geography." },
{ id: 286, emoji: "🌏", name: "Earth Globe Asia-Australia", meaning: "The Earth globe focused on Asia and Australia, often representing the world or geography." },
{ id: 287, emoji: "🌋", name: "Volcano", meaning: "A volcano, often representing natural disasters or eruptions." },
{ id: 288, emoji: "📱", name: "Mobile Phone", meaning: "A mobile phone, representing communication or technology." },
{ id: 289, emoji: "📲", name: "Mobile Phone with Arrow", meaning: "A mobile phone with an arrow indicating a download or upload." },
{ id: 290, emoji: "💻", name: "Laptop Computer", meaning: "A laptop computer, representing computing or work." },
{ id: 291, emoji: "🖥️", name: "Desktop Computer", meaning: "A desktop computer, representing work or technology." },
{ id: 292, emoji: "🖨️", name: "Printer", meaning: "A printer, used for printing documents or images." },
{ id: 293, emoji: "⌨️", name: "Keyboard", meaning: "A keyboard, used for typing on computers or devices." },
{ id: 294, emoji: "🖱️", name: "Mouse", meaning: "A computer mouse, used for navigating on a computer screen." },
{ id: 295, emoji: "🖲️", name: "Trackball", meaning: "A trackball, a pointing device used to control the cursor on a screen." },
{ id: 296, emoji: "💽", name: "Minidisc", meaning: "A minidisc, representing portable storage media." },
{ id: 297, emoji: "💾", name: "Floppy Disk", meaning: "A floppy disk, an older form of data storage." },
{ id: 298, emoji: "💿", name: "Optical Disk", meaning: "An optical disk, used for storing data or media." },
{ id: 299, emoji: "📀", name: "DVD", meaning: "A DVD, used for storing and playing digital video." },
{ id: 300, emoji: "📼", name: "Videocassette", meaning: "A videocassette, used for recording and playing video tapes." },
{ id: 301, emoji: "📷", name: "Camera", meaning: "A camera, used for taking photographs or videos." },
{ id: 302, emoji: "📸", name: "Camera with Flash", meaning: "A camera with a flash, used for taking photos in low light." },
{ id: 303, emoji: "📹", name: "Video Camera", meaning: "A video camera, used for recording videos." },
{ id: 304, emoji: "📺", name: "Television", meaning: "A television, used for watching broadcasts or shows." },
{ id: 305, emoji: "📻", name: "Radio", meaning: "A radio, used for listening to broadcasts." },
{ id: 306, emoji: "🎙️", name: "Microphone", meaning: "A microphone, used for recording or amplifying sound." },
{ id: 307, emoji: "🎚️", name: "Level Slider", meaning: "A level slider, used for adjusting volume or settings." },
{ id: 308, emoji: "🎛️", name: "Control Knobs", meaning: "Control knobs, used for adjusting various settings or functions." },
{ id: 309, emoji: "🔊", name: "Loudspeaker", meaning: "A loudspeaker, used for amplifying sound." },
{ id: 310, emoji: "🔉", name: "Medium Volume", meaning: "A speaker with medium volume, representing audio levels." },
{ id: 311, emoji: "🔈", name: "Low Volume", meaning: "A speaker with low volume, representing audio levels." },
{ id: 312, emoji: "🔇", name: "Mute", meaning: "A speaker with a mute symbol, indicating no sound." },
{ id: 313, emoji: "📢", name: "Loudspeaker with Sound", meaning: "A loudspeaker emitting sound, used for announcements or alerts." },
{ id: 314, emoji: "📣", name: "Megaphone", meaning: "A megaphone, used for amplifying the voice or making announcements." },
{ id: 315, emoji: "🔔", name: "Bell", meaning: "A bell, used for notifications or alerts." },
{ id: 316, emoji: "🔕", name: "Bell with Slash", meaning: "A bell with a slash, indicating silent or no notifications." },
{ id: 317, emoji: "🕰️", name: "Mantelpiece Clock", meaning: "A mantelpiece clock, used for telling time." },
{ id: 318, emoji: "⌚", name: "Watch", meaning: "A wristwatch, used for telling time." },
{ id: 319, emoji: "⏰", name: "Alarm Clock", meaning: "An alarm clock, used for setting alarms or reminders." },
{ id: 320, emoji: "⏱️", name: "Stopwatch", meaning: "A stopwatch, used for measuring time intervals." },
{ id: 321, emoji: "⏲️", name: "Timer Clock", meaning: "A timer clock, used for countdowns or timing events." },
{ id: 322, emoji: "🕰️", name: "Clock Face Twelve O'Clock", meaning: "A clock showing twelve o'clock, used for representing time." },
{ id: 323, emoji: "🕛", name: "Clock Face Twelve-Thirty", meaning: "A clock showing twelve-thirty, used for representing time." },
{ id: 324, emoji: "🕧", name: "Clock Face Twelve-Thirty", meaning: "A clock showing twelve-thirty, used for representing time." },
{ id: 325, emoji: "🕐", name: "Clock Face One O'Clock", meaning: "A clock showing one o'clock, used for representing time." },
{ id: 326, emoji: "🕑", name: "Clock Face One-Thirty", meaning: "A clock showing one-thirty, used for representing time." },
{ id: 327, emoji: "🕒", name: "Clock Face Two O'Clock", meaning: "A clock showing two o'clock, used for representing time." },
{ id: 328, emoji: "🕓", name: "Clock Face Two-Thirty", meaning: "A clock showing two-thirty, used for representing time." },
{ id: 329, emoji: "🕔", name: "Clock Face Three O'Clock", meaning: "A clock showing three o'clock, used for representing time." },
{ id: 330, emoji: "🕕", name: "Clock Face Three-Thirty", meaning: "A clock showing three-thirty, used for representing time." },
{ id: 331, emoji: "🕖", name: "Clock Face Four O'Clock", meaning: "A clock showing four o'clock, used for representing time." },
{ id: 332, emoji: "🕗", name: "Clock Face Four-Thirty", meaning: "A clock showing four-thirty, used for representing time." },
{ id: 333, emoji: "🕘", name: "Clock Face Five O'Clock", meaning: "A clock showing five o'clock, used for representing time." },
{ id: 334, emoji: "🕙", name: "Clock Face Five-Thirty", meaning: "A clock showing five-thirty, used for representing time." },
{ id: 335, emoji: "🕚", name: "Clock Face Six O'Clock", meaning: "A clock showing six o'clock, used for representing time." },
{ id: 336, emoji: "🕛", name: "Clock Face Six-Thirty", meaning: "A clock showing six-thirty, used for representing time." },
{ id: 337, emoji: "🕜", name: "Clock Face Seven O'Clock", meaning: "A clock showing seven o'clock, used for representing time." },
{ id: 338, emoji: "🕝", name: "Clock Face Seven-Thirty", meaning: "A clock showing seven-thirty, used for representing time." },
{ id: 339, emoji: "🕞", name: "Clock Face Eight O'Clock", meaning: "A clock showing eight o'clock, used for representing time." },
{ id: 340, emoji: "🕟", name: "Clock Face Eight-Thirty", meaning: "A clock showing eight-thirty, used for representing time." },
{ id: 341, emoji: "🕠", name: "Clock Face Nine O'Clock", meaning: "A clock showing nine o'clock, used for representing time." },
{ id: 342, emoji: "🕡", name: "Clock Face Nine-Thirty", meaning: "A clock showing nine-thirty, used for representing time." },
{ id: 343, emoji: "🕢", name: "Clock Face Ten O'Clock", meaning: "A clock showing ten o'clock, used for representing time." },
{ id: 344, emoji: "🕣", name: "Clock Face Ten-Thirty", meaning: "A clock showing ten-thirty, used for representing time." },
{ id: 345, emoji: "🕤", name: "Clock Face Eleven O'Clock", meaning: "A clock showing eleven o'clock, used for representing time." },
{ id: 346, emoji: "🕥", name: "Clock Face Eleven-Thirty", meaning: "A clock showing eleven-thirty, used for representing time." },
{ id: 347, emoji: "🕦", name: "Clock Face Twelve O'Clock", meaning: "A clock showing twelve o'clock, used for representing time." },
{ id: 348, emoji: "🕧", name: "Clock Face Twelve-Thirty", meaning: "A clock showing twelve-thirty, used for representing time." },
{ id: 349, emoji: "🕯️", name: "Candle", meaning: "A candle, used for illumination or decoration." },
{ id: 350, emoji: "💡", name: "Light Bulb", meaning: "A light bulb, representing ideas or illumination." },
{ id: 351, emoji: "🔦", name: "Flashlight", meaning: "A flashlight, used for lighting in the dark." },
{ id: 352, emoji: "🏮", name: "Red Paper Lantern", meaning: "A red paper lantern, often used in festivals or decorations." },
{ id: 353, emoji: "🪔", name: "Diya Lamp", meaning: "A diya lamp, used in South Asian cultures for lighting." },
{ id: 354, emoji: "🔧", name: "Wrench", meaning: "A wrench, used for mechanical adjustments or repairs." },
{ id: 355, emoji: "🔩", name: "Nut and Bolt", meaning: "A nut and bolt, representing hardware or construction." },
{ id: 356, emoji: "🔨", name: "Hammer", meaning: "A hammer, used for construction or repairs." },
{ id: 357, emoji: "🔪", name: "Kitchen Knife", meaning: "A kitchen knife, used for cutting food." },
{ id: 358, emoji: "🗡️", name: "Dagger", meaning: "A dagger, used as a weapon or symbolically." },
{ id: 359, emoji: "⚔️", name: "Crossed Swords", meaning: "Two crossed swords, representing conflict or battle." },
{ id: 360, emoji: "🛡️", name: "Shield", meaning: "A shield, used for protection or defense." },
{ id: 361, emoji: "🚪", name: "Door", meaning: "A door, representing entry or exit." },
{ id: 362, emoji: "🛋️", name: "Couch and Lamp", meaning: "A couch with a lamp, representing home or relaxation." },
{ id: 363, emoji: "🛏️", name: "Bed", meaning: "A bed, representing sleep or rest." },
{ id: 364, emoji: "🛁", name: "Bath", meaning: "A bath, used for washing or relaxation." },
{ id: 365, emoji: "🚿", name: "Shower", meaning: "A shower, used for bathing." },
{ id: 366, emoji: "🛀", name: "Bath", meaning: "A bath, used for relaxation or hygiene." },
{ id: 367, emoji: "🧼", name: "Soap", meaning: "A bar of soap, used for cleaning." },
{ id: 368, emoji: "🧽", name: "Sponge", meaning: "A sponge, used for cleaning or washing." },
{ id: 369, emoji: "🧴", name: "Lotion Bottle", meaning: "A bottle of lotion, used for skincare." },
{ id: 370, emoji: "🧹", name: "Broom", meaning: "A broom, used for cleaning." },
{ id: 371, emoji: "🧺", name: "Basket", meaning: "A basket, used for carrying items or laundry." },
{ id: 372, emoji: "🧻", name: "Roll of Paper", meaning: "A roll of paper, often used as a towel or tissue." },
{ id: 373, emoji: "🧯", name: "Fire Extinguisher", meaning: "A fire extinguisher, used for safety in case of fire." },
{ id: 374, emoji: "🔑", name: "Key", meaning: "A key, used for locking or unlocking things." },
{ id: 375, emoji: "🗝️", name: "Old Key", meaning: "An old-fashioned key, often representing antiques or nostalgia." },
{ id: 376, emoji: "🔐", name: "Locked with Key", meaning: "A lock with a key, representing security or privacy." },
{ id: 377, emoji: "🔓", name: "Unlocked", meaning: "An unlocked padlock, representing accessibility or freedom." },
{ id: 378, emoji: "🔒", name: "Locked", meaning: "A locked padlock, representing security or privacy." },
{ id: 379, emoji: "🔏", name: "Lock with Ink Pen", meaning: "A padlock with a pen, often representing secrecy or protection of information." },
{ id: 380, emoji: "🔍", name: "Magnifying Glass Tilted Left", meaning: "A magnifying glass tilted left, used for searching or examining." },
{ id: 381, emoji: "🔎", name: "Magnifying Glass Tilted Right", meaning: "A magnifying glass tilted right, used for searching or examining." },
{ id: 382, emoji: "🔬", name: "Microscope", meaning: "A microscope, used for scientific examination or research." },
{ id: 383, emoji: "🔭", name: "Telescope", meaning: "A telescope, used for viewing distant objects." },
{ id: 384, emoji: "📡", name: "Satellite Antenna", meaning: "A satellite antenna, used for communication or broadcasting." },
{ id: 385, emoji: "💉", name: "Syringe", meaning: "A syringe, used for medical injections or vaccinations." },
{ id: 386, emoji: "💊", name: "Pill", meaning: "A pill, representing medication or health." },
{ id: 387, emoji: "🚬", name: "Cigarette", meaning: "A cigarette, representing smoking or tobacco." },
{ id: 388, emoji: "⚗️", name: "Alembic", meaning: "An alembic, used for distillation in chemistry." },
{ id: 389, emoji: "🔭", name: "Telescope", meaning: "A telescope, used for viewing distant objects." },
{ id: 390, emoji: "🔬", name: "Microscope", meaning: "A microscope, used for scientific examination or research." },
{ id: 391, emoji: "🧪", name: "Test Tube", meaning: "A test tube, used for chemical experiments." },
{ id: 392, emoji: "🧫", name: "Petri Dish", meaning: "A petri dish, used for growing cultures in scientific experiments." },
{ id: 393, emoji: "🧬", name: "DNA Double Helix", meaning: "A DNA double helix, representing genetics or biology." },
{ id: 394, emoji: "🧮", name: "Abacus", meaning: "An abacus, used for calculations or arithmetic." },
{ id: 395, emoji: "🔒", name: "Locked", meaning: "A padlock, representing security or privacy." },
{ id: 396, emoji: "🔓", name: "Unlocked", meaning: "An unlocked padlock, representing accessibility or freedom." },
{ id: 397, emoji: "🔏", name: "Lock with Ink Pen", meaning: "A padlock with a pen, often representing secrecy or protection of information." },
{ id: 398, emoji: "🍹", name: "Tropical Drink", meaning: "A colorful tropical drink, often associated with vacations or relaxation." },
{ id: 399, emoji: "🍸", name: "Cocktail Glass", meaning: "A cocktail glass, typically used for serving mixed alcoholic beverages." },
{ id: 400, emoji: "🍷", name: "Wine Glass", meaning: "A wine glass, used for serving red or white wine." },
{ id: 401, emoji: "🍺", name: "Beer Mug", meaning: "A mug of beer, representing a cold alcoholic beverage." },
{ id: 402, emoji: "🍻", name: "Clinking Beer Mugs", meaning: "Two beer mugs clinking together, representing celebration or toasting." },
{ id: 403, emoji: "🥂", name: "Clinking Glasses", meaning: "Two glasses clinking together, often used to celebrate or make a toast." },
{ id: 404, emoji: "🥃", name: "Tumbler Glass", meaning: "A tumbler glass, used for serving whiskey or other spirits." },
{ id: 405, emoji: "🥤", name: "Cup with Straw", meaning: "A cup with a straw, representing a non-alcoholic beverage like a soft drink." },
{ id: 406, emoji: "🧃", name: "Juice Box", meaning: "A juice box, commonly used for serving fruit juice, especially to children." },
{ id: 407, emoji: "🧉", name: "Mate", meaning: "A cup of mate, a traditional South American beverage made from yerba mate leaves." },
{ id: 408, emoji: "🍼", name: "Baby Bottle", meaning: "A baby bottle, used for feeding infants with milk or formula." },
{ id: 409, emoji: "☕", name: "Hot Beverage", meaning: "A cup of coffee or tea, representing a hot drink." },
{ id: 410, emoji: "🧊", name: "Ice", meaning: "An ice cube, used to chill drinks." },
{ id: 411, emoji: "🥛", name: "Glass of Milk", meaning: "A glass of milk, representing dairy or nutrition." },
{ id: 412, emoji: "🍶", name: "Sake Bottle", meaning: "A bottle of sake, a Japanese rice wine." },
{ id: 413, emoji: "🍾", name: "Bottle with Popping Cork", meaning: "A champagne bottle with a popping cork, representing celebration." },
{ id: 414, emoji: "🥥", name: "Coconut", meaning: "A coconut, often associated with tropical drinks or desserts." },
{ id: 415, emoji: "🍴", name: "Fork and Knife", meaning: "A fork and knife, used for eating meals." },
{ id: 416, emoji: "📚", name: "Books", meaning: "A stack of books, representing reading or education." },
{ id: 417, emoji: "📖", name: "Open Book", meaning: "An open book, often used to represent reading or studying." },
{ id: 418, emoji: "📓", name: "Notebook", meaning: "A notebook, used for writing or taking notes." },
{ id: 419, emoji: "📒", name: "Ledger", meaning: "A ledger, often used for accounting or record-keeping." },
{ id: 420, emoji: "📕", name: "Closed Book", meaning: "A closed book, representing a book that is not being read." },
{ id: 421, emoji: "📗", name: "Green Book", meaning: "A green book, used to represent reading or studying." },
{ id: 422, emoji: "📘", name: "Blue Book", meaning: "A blue book, representing a book or educational material." },
{ id: 423, emoji: "📙", name: "Orange Book", meaning: "An orange book, used to represent reading or education." },
{ id: 424, emoji: "📝", name: "Memo", meaning: "A memo or note, used for writing reminders or messages." },
{ id: 425, emoji: "✏️", name: "Pencil", meaning: "A pencil, used for writing or drawing." },
{ id: 426, emoji: "🖋️", name: "Fountain Pen", meaning: "A fountain pen, used for elegant or formal writing." },
{ id: 427, emoji: "🖊️", name: "Pen", meaning: "A pen, used for writing." },
{ id: 428, emoji: "🖌️", name: "Paintbrush", meaning: "A paintbrush, used for painting or art." },
{ id: 429, emoji: "🖍️", name: "Crayon", meaning: "A crayon, used for coloring or drawing." },
{ id: 430, emoji: "🖨️", name: "Printer", meaning: "A printer, used for printing documents or images." },
{ id: 431, emoji: "📝", name: "Memo", meaning: "A memo or note, often used for reminders or jotting down information." },
{ id: 432, emoji: "⚽", name: "Soccer Ball", meaning: "A soccer ball, representing the sport of soccer." },
{ id: 433, emoji: "🏀", name: "Basketball", meaning: "A basketball, used in the sport of basketball." },
{ id: 434, emoji: "🏈", name: "American Football", meaning: "An American football, used in the sport of football." },
{ id: 435, emoji: "⚾", name: "Baseball", meaning: "A baseball, used in the sport of baseball." },
{ id: 436, emoji: "🥎", name: "Softball", meaning: "A softball, used in the sport of softball." },
{ id: 437, emoji: "🏐", name: "Volleyball", meaning: "A volleyball, used in the sport of volleyball." },
{ id: 438, emoji: "🏉", name: "Rugby Football", meaning: "A rugby ball, used in the sport of rugby." },
{ id: 439, emoji: "🎱", name: "Pool 8 Ball", meaning: "An 8 ball, used in the game of pool or billiards." },
{ id: 440, emoji: "🎳", name: "Bowling", meaning: "A bowling ball and pins, representing the sport of bowling." },
{ id: 441, emoji: "🏌️‍♂️", name: "Man Golfing", meaning: "A man playing golf." },
{ id: 442, emoji: "🏌️‍♀️", name: "Woman Golfing", meaning: "A woman playing golf." },
{ id: 443, emoji: "⛳", name: "Flag in Hole", meaning: "A flag in a hole on a golf course." },
{ id: 444, emoji: "🛹", name: "Skateboard", meaning: "A skateboard, used for skateboarding." },
{ id: 445, emoji: "🛼", name: "Roller Skate", meaning: "A roller skate, used for roller skating." },
{ id: 446, emoji: "🎣", name: "Fishing Pole", meaning: "A fishing pole, used for fishing." },
{ id: 447, emoji: "🤿", name: "Goggles", meaning: "Goggles, used for swimming or other activities requiring eye protection." },
{ id: 448, emoji: "🥋", name: "Martial Arts Uniform", meaning: "A martial arts uniform, used in various martial arts practices." },
{ id: 449, emoji: "🥅", name: "Goal Net", meaning: "A net used for scoring in sports such as soccer or hockey." },
{ id: 450, emoji: "🎯", name: "Direct Hit", meaning: "A target with an arrow hitting the bullseye, representing precision or aim." },
{ id: 451, emoji: "🏆", name: "Trophy", meaning: "A trophy, representing an award or achievement in sports or other competitions." },
{ id: 452, emoji: "🥇", name: "1st Place Medal", meaning: "A gold medal, awarded for first place in a competition." },
{ id: 453, emoji: "🥈", name: "2nd Place Medal", meaning: "A silver medal, awarded for second place in a competition." },
{ id: 454, emoji: "🥉", name: "3rd Place Medal", meaning: "A bronze medal, awarded for third place in a competition." },
{ id: 455, emoji: "🎫", name: "Ticket", meaning: "A ticket, often used for events, travel, or entry." },
{ id: 456, emoji: "⛸️", name: "Ice Skate", meaning: "An ice skate, used for ice skating." },
{ id: 457, emoji: "🧗‍♂️", name: "Man Climbing", meaning: "A man climbing, representing rock climbing or mountaineering." },
{ id: 458, emoji: "🧗‍♀️", name: "Woman Climbing", meaning: "A woman climbing, representing rock climbing or mountaineering." },
{ id: 459, emoji: "🚴‍♂️", name: "Man Biking", meaning: "A man riding a bicycle." },
{ id: 460, emoji: "🚴‍♀️", name: "Woman Biking", meaning: "A woman riding a bicycle." },
{ id: 461, emoji: "🚵‍♂️", name: "Man Mountain Biking", meaning: "A man riding a mountain bike." },
{ id: 462, emoji: "🚵‍♀️", name: "Woman Mountain Biking", meaning: "A woman riding a mountain bike." },
{ id: 463, emoji: "🏇", name: "Horse Racing", meaning: "A jockey riding a horse, representing horse racing." },
{ id: 464, emoji: "💃", name: "Woman Dancing", meaning: "A woman dancing, often used to represent dancing or celebration." },
  { id: 465, emoji: "🕺", name: "Man Dancing", meaning: "A man dancing, often used to represent dancing or celebration." },
  { id: 466, emoji: "🩰", name: "Ballet Shoes", meaning: "Ballet shoes, used for ballet dancing." },
  { id: 467, emoji: "👯‍♂️", name: "Men with Bunny Ears", meaning: "Two men with bunny ears, often used to represent dancing or celebration." },
  { id: 468, emoji: "👯‍♀️", name: "Women with Bunny Ears", meaning: "Two women with bunny ears, often used to represent dancing or celebration." },
  { id: 469, emoji: "🕴️", name: "Man in Suit Levitating", meaning: "A man in a suit appearing to be floating or dancing, often used to represent a cool or stylish dance." },
  { id: 470, emoji: "🪅", name: "Piñata", meaning: "A piñata, used in festive celebrations and parties, often associated with dancing and games." },
  { id: 471, emoji: "🪘", name: "Maracas", meaning: "Maracas, used in music and dance, particularly in Latin American cultures." },
  { id: 472, emoji: "👕", name: "T-Shirt", meaning: "A short-sleeved t-shirt, typically worn casually." },
  { id: 473, emoji: "👔", name: "Necktie", meaning: "A necktie, often worn with formal attire." },
  { id: 474, emoji: "👗", name: "Dress", meaning: "A dress, typically worn by women or girls for formal or casual occasions." },
  { id: 475, emoji: "👘", name: "Kimono", meaning: "A kimono, a traditional Japanese garment." },
  { id: 476, emoji: "👙", name: "Bikini", meaning: "A bikini, a type of two-piece swimsuit." },
  { id: 477, emoji: "👚", name: "Woman’s Clothes", meaning: "Clothing traditionally worn by women, such as a blouse or dress." },
  { id: 478, emoji: "👛", name: "Purse", meaning: "A small handbag or purse, used for carrying personal items." },
  { id: 479, emoji: "👜", name: "Handbag", meaning: "A handbag, used for carrying personal belongings." },
  { id: 480, emoji: "👝", name: "Clutch Bag", meaning: "A clutch bag, often used for formal occasions." },
  { id: 481, emoji: "👞", name: "Mans Shoe", meaning: "A man’s dress shoe, typically worn with formal attire." },
  { id: 482, emoji: "👟", name: "Running Shoe", meaning: "A running shoe, used for athletic activities or casual wear." },
  { id: 483, emoji: "👠", name: "High-Heeled Shoe", meaning: "A high-heeled shoe, typically worn for formal or dressy occasions." },
  { id: 484, emoji: "👡", name: "Womans Sandal", meaning: "A woman’s sandal, used for casual or warm weather wear." },
  { id: 485, emoji: "👢", name: "Lapel Pin", meaning: "A lapel pin, often worn on the lapel of a jacket or coat." },
  { id: 486, emoji: "👗", name: "Dress", meaning: "A dress, often worn for formal or casual occasions." },
  { id: 487, emoji: "👚", name: "Woman’s Clothes", meaning: "Clothing traditionally worn by women, such as a blouse or dress." },
  { id: 488, emoji: "👠", name: "High-Heeled Shoe", meaning: "A high-heeled shoe, used for formal occasions." },
  { id: 489, emoji: "🧤", name: "Gloves", meaning: "A pair of gloves, used for warmth or protection." },
  { id: 490, emoji: "🧣", name: "Scarf", meaning: "A scarf, used for warmth or fashion." },
  { id: 491, emoji: "🧥", name: "Coat", meaning: "A coat, used for warmth or protection from the weather." },
  { id: 492, emoji: "🧦", name: "Socks", meaning: "A pair of socks, worn on the feet for comfort or warmth." },
  { id: 493, emoji: "🧢", name: "Billed Cap", meaning: "A billed cap, used for sun protection or casual wear." },
  { id: 494, emoji: "🔊", name: "Speaker High Volume", meaning: "A speaker emitting sound at high volume." },
  { id: 495, emoji: "🔉", name: "Speaker Medium Volume", meaning: "A speaker emitting sound at medium volume." },
  { id: 496, emoji: "🔈", name: "Speaker Low Volume", meaning: "A speaker emitting sound at low volume." },
  { id: 497, emoji: "🔇", name: "Mute", meaning: "A speaker with a slash through it, indicating that sound is muted." },
  { id: 498, emoji: "🔔", name: "Bell", meaning: "A bell, often used to indicate a notification or alert." },
  { id: 499, emoji: "📱", name: "Mobile Phone", meaning: "A mobile phone, representing communication or technology." },
  { id: 500, emoji: "📲", name: "Mobile Phone with Arrow", meaning: "A mobile phone with an arrow, often used to represent sending or receiving information." },
  { id: 501, emoji: "📞", name: "Telephone Receiver", meaning: "A telephone receiver, representing phone calls or communication." },
  { id: 502, emoji: "☎️", name: "Telephone", meaning: "A classic telephone, used for voice communication." },
  { id: 503, emoji: "📶", name: "Antenna Bars", meaning: "Bars indicating mobile network signal strength." },
  { id: 504, emoji: "🥚", name: "Egg", meaning: "A chicken egg, often used to represent food or cooking." },
  { id: 505, emoji: "🍳", name: "Cooking", meaning: "An egg being cooked, typically representing breakfast or cooking." }
];
export default emojipedia;
